### ISSUE TITLE
[Error Reporting] No environment variables

### ISSUE THREAD

**Issue by cbfx** [rackerlabs/yolo#5]
If no environment variables are present, yolo returns a python stack trace.

As a developer, it would be useful if yolo told me what was missing so that I can quickly recover if I'm too lazy to read the documentation. : )

**Comment by larsbutler** [comment]
> As a developer, it would be useful if yolo told me what was missing so that I can quickly recover if I'm too lazy to read the documentation. : )

I completely agree, thanks for pointing this out.
